<?php
return [
    'categories' => [
        'POPS＆アニメ',
        'niconico＆ボーカロイド',
        'ゲーム＆バラエティ',
        '東方Project',
        'maimai',
        'オンゲキ＆CHUNITHM',
    ],
    'versions' => [
        'maimai',
        'maimai PLUS',
        'GreeN',
        'GreeN PLUS',
        'ORANGE',
        'ORANGE PLUS',
        'PiNK',
        'PiNK PLUS',
        'MURASAKi',
        'MURASAKi PLUS',
        'MiLK',
        'MiLK PLUS',
        'FiNALE',
        'maimaiでらっくす',
        'maimaiでらっくす PLUS',
        'Splash',
        'Splash PLUS',
        'UNiVERSE',
        'UNiVERSE PLUS',
    ],
    'levels' => [
        '15' => '15',
        '14.5' => '14+',
        '14' => '14',
        '13.5' => '13+',
        '13' => '13',
        '12.5' => '12+',
        '12' => '12',
        '11.5' => '11+',
        '11' => '11',
        '10.5' => '10+',
        '10' => '10',
        '9.5' => '9+',
        '9' => '9',
        '8.5' => '8+',
        '8' => '8',
        '7.5' => '7+',
        '7' => '7',
        '6' => '6',
        '5' => '5',
        '4' => '4',
        '3' => '3',
        '2' => '2',
        '1' => '1',
    ],
    'difficulties' => [
        'basic' => 'Basic',
        'advance' => 'Advanced',
        'expert' => 'Expert',
        'master' => 'Master',
        'remaster' => 'Re:Master'
    ],
];